version: '3.3'
services:

  db:
    image: mysql:latest
    container_name: crud-db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: crud
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    volumes:
      - crud_db:/var/lib/mysql
    networks:
      - mynet

  app:
    build: .
    container_name: crud-app
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - db
    networks:
      - mynet

volumes:
  crud_db:

networks: 
  mynet:
