services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
  
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: 