services:
  db:
    image: mysql:latest
    container_name: crud-db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: crud
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    volumes:
      - crud_db:/var/lib/mysql
    networks:
      - networks

  app:  
    build: .
    container_name: app-crud
    restart: always
    ports:
      - "100:3000"
    depends_on:
      - db
    networks:
      - networks

volumes:
  crud_db:

networks:
  networks:

