services:
  db:
    image: mysql:latest
    container_name: wordpress-db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 123
    volumes:
      - wordpress_db:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress-web
    depends_on:
      - db
    ports:
      - "8084:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_web:/var/www/html

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wordpress-php
    depends_on:
      - db
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123

volumes:
  wordpress_db:
  wordpress_web: